### ISSUE TITLE
Unnecessary css duplication

### ISSUE THREAD

**Issue by lifeiscontent** [MysticalCabbage/MysticalCabbage#116]
``` css
.teacherDashboard, .classroomDashboard, .reportsDashboard, .homeworkDashboard{
  background-size: cover;
  background: url("../assets/background.png") no-repeat center center fixed;
  height: 100vh;
  overflow: scroll;
}
```

rather than duplicating this style over and over, why not just call it `.dashboard`?
